export interface User {
    id?: string;
    document: string,
    typeDocument: string,
    username: string,
    fullName: string,
    dateOfBirth: string,
    state: string,
    city: string,
    gender: string,
    race: string,
    category: string,
    typeOfPhone: string,
    phoneNumber: string,
    ownerName: string,
    typeOfCoagulopathy: string,
    severityOfCoagulopathy: string,
    callCenterLocation: string,
    password: string,
    pcd: boolean,
    typeOfDisability: string,
    email: string,
    roleUser: string,
    profilePictureURL: string
}